title: lemke.ai
email: 1@lemke.ai
baseurl: ""
url: "https://lemke.ai"
github_username: chrislemke
linkedin_username: chrismlemke
medium_username: chrislemke
pypi_username: chrislemke
kaggle_username: christopherlemke
paginate: 1
paginate_path: "/baseurl/page:num/"

nav:
  - title: posts
    url: /posts

  - title: about
    url: /about

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
